import type { UserProfile, UserRole } from '../../domains/auth/types';

export const MOCK_USERS: Record<UserRole, UserProfile> = {
  resident: {
    id: 'user-resident-01',
    name: 'Sarvesh Kulkarni',
    phone: '9876543210',
    role: 'resident',
    roleLabel: 'Resident / Owner',
    societyName: 'Green Valley Society',
    flatDetails: 'Tower B · Flat 1204',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    designation: 'Flat Owner & Resident',
    statusBadge: 'Verified Resident',
  },
  secretary: {
    id: 'user-secretary-01',
    name: 'Mayuri Udar',
    phone: '9820012345',
    role: 'secretary',
    roleLabel: 'Society Secretary',
    societyName: 'Green Valley Society',
    flatDetails: 'Block A · Flat 101',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80',
    designation: 'Management Committee Secretary',
    statusBadge: 'Managing Committee',
  },
  guard: {
    id: 'user-guard-01',
    name: 'Officer R. Singh',
    phone: '9123456789',
    role: 'guard',
    roleLabel: 'Chief Security Officer',
    societyName: 'Green Valley Society',
    flatDetails: 'Gate #1 North Terminal',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    designation: 'Senior Gate Security Officer',
    statusBadge: 'On Duty · Shift A',
  },
  committee: {
    id: 'user-committee-01',
    name: 'Rajesh Mehta',
    phone: '9900112233',
    role: 'committee',
    roleLabel: 'Committee Member',
    societyName: 'Green Valley Society',
    flatDetails: 'Tower A · Flat 201',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=250&q=80',
    designation: 'Management Committee Member',
    statusBadge: 'Committee',
  },
  facility_manager: {
    id: 'user-fm-01',
    name: 'Suresh Patil',
    phone: '9811223344',
    role: 'facility_manager',
    roleLabel: 'Facility Manager',
    societyName: 'Green Valley Society',
    flatDetails: 'Office Block',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    designation: 'Facility & Operations Manager',
    statusBadge: 'Operations',
  },
  staff: {
    id: 'user-staff-01',
    name: 'Ramesh Kumar',
    phone: '9833445566',
    role: 'staff',
    roleLabel: 'Society Staff',
    societyName: 'Green Valley Society',
    designation: 'Maintenance Staff',
    statusBadge: 'Active',
  },
  vendor: {
    id: 'user-vendor-01',
    name: 'Priya Cleaning Services',
    phone: '9844556677',
    role: 'vendor',
    roleLabel: 'Vendor / Service Provider',
    societyName: 'Green Valley Society',
    designation: 'Registered Vendor',
    statusBadge: 'Verified Vendor',
  },
  contractor: {
    id: 'user-contractor-01',
    name: 'BuildRight Contractors',
    phone: '9855667788',
    role: 'contractor',
    roleLabel: 'Contractor',
    societyName: 'Green Valley Society',
    designation: 'Licensed Contractor',
    statusBadge: 'Active Contract',
  },
  admin: {
    id: 'user-admin-01',
    name: 'Platform Admin',
    phone: '9000000001',
    role: 'admin',
    roleLabel: 'Platform Administrator',
    societyName: 'CommunityOS Platform',
    designation: 'System Administrator',
    statusBadge: 'Admin',
  },
};


