import type { UserProfile, UserRole } from '../../domains/auth/types';

export const MOCK_USERS: Record<UserRole, UserProfile> = {
  resident: {
    id: 'user-resident-01',
    uid: 'user-resident-01',
    name: 'Sarvesh Kulkarni',
    phone: '9876543210',
    email: 'sarvesh@greenvalley.com',
    role: 'resident',
    roleLabel: 'Resident / Owner',
    societyId: 'soc-gvs',
    societyName: 'Green Valley Society',
    flatNumber: 'B-1204',
    flatDetails: 'Tower B · Flat 1204',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    designation: 'Flat Owner & Resident',
    statusBadge: 'Verified Resident',
  },
  secretary: {
    id: 'user-secretary-01',
    uid: 'user-secretary-01',
    name: 'Mayuri Udar',
    phone: '9820012345',
    email: 'secretary@greenvalley.com',
    role: 'secretary',
    roleLabel: 'Society Secretary',
    societyId: 'soc-gvs',
    societyName: 'Green Valley Society',
    flatNumber: 'A-101',
    flatDetails: 'Block A · Flat 101',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80',
    designation: 'Management Committee Secretary',
    statusBadge: 'Managing Committee',
  },
  guard: {
    id: 'user-guard-01',
    uid: 'user-guard-01',
    name: 'Officer R. Singh',
    phone: '9123456789',
    email: 'guard1@greenvalley.com',
    role: 'guard',
    roleLabel: 'Chief Security Officer',
    societyId: 'soc-gvs',
    societyName: 'Green Valley Society',
    flatDetails: 'Gate #1 North Terminal',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    designation: 'Senior Gate Security Officer',
    statusBadge: 'On Duty · Shift A',
  },
  committee: {
    id: 'user-committee-01',
    uid: 'user-committee-01',
    name: 'Rajesh Mehta',
    phone: '9900112233',
    email: 'rajesh.committee@greenvalley.com',
    role: 'committee',
    roleLabel: 'Committee Member',
    societyId: 'soc-gvs',
    societyName: 'Green Valley Society',
    flatNumber: 'A-201',
    flatDetails: 'Tower A · Flat 201',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=250&q=80',
    designation: 'Management Committee Member',
    statusBadge: 'Committee',
  },
  facility_manager: {
    id: 'user-fm-01',
    uid: 'user-fm-01',
    name: 'Suresh Patil',
    phone: '9811223344',
    email: 'facility@greenvalley.com',
    role: 'facility_manager',
    roleLabel: 'Facility Manager',
    societyId: 'soc-gvs',
    societyName: 'Green Valley Society',
    flatDetails: 'Office Block',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    designation: 'Facility & Operations Manager',
    statusBadge: 'Operations',
  },
  vendor: {
    id: 'user-vendor-01',
    uid: 'user-vendor-01',
    name: 'Priya Cleaning Services',
    phone: '9844556677',
    email: 'priya.vendor@greenvalley.com',
    role: 'vendor',
    roleLabel: 'Vendor / Service Provider',
    societyId: 'soc-gvs',
    societyName: 'Green Valley Society',
    designation: 'Registered Vendor',
    status: 'ACTIVE',
    statusBadge: 'Verified Vendor',
  },
  admin: {
    id: 'user-admin-01',
    uid: 'user-admin-01',
    name: 'Platform Admin',
    phone: '9000000001',
    email: 'admin@aarizo.com',
    role: 'admin',
    roleLabel: 'Platform Administrator',
    societyId: 'soc-gvs',
    societyName: 'CommunityOS Platform',
    designation: 'System Administrator',
    status: 'ACTIVE',
    statusBadge: 'Admin',
  },
};


