import type { VisitorPass } from '../../domains/visitors';

export const initialMockVisitorPasses: VisitorPass[] = [
  {
    id: 'pass-8492',
    passcode: '8492',
    visitorType: 'guest',
    visitorName: 'Rahul Sharma',
    visitorPhone: '+91 98765 43210',
    flatCode: '1204',
    tower: 'Tower B',
    societyName: 'Lakeview Residency',
    expectedDate: 'Today (06 Sep 2026)',
    expectedTimeSlot: '06:00 PM – 09:00 PM',
    status: 'active',
    createdAt: 'Today, 02:15 PM',
    validUntil: 'Today, 11:59 PM',
    gateName: 'Main Gate #1',
    notes: 'Family dinner visit',
  },
  {
    id: 'pass-4921',
    passcode: '4921',
    visitorType: 'delivery',
    visitorName: 'Food Delivery Agent',
    companyName: 'Express Delivery',
    flatCode: '1204',
    tower: 'Tower B',
    societyName: 'Lakeview Residency',
    expectedDate: 'Today (06 Sep 2026)',
    expectedTimeSlot: 'Just now',
    status: 'approval_required',
    createdAt: 'Today, 02:30 PM',
    validUntil: 'Today, 03:30 PM',
    gateName: 'Main Gate #1',
    notes: 'Food parcel at security gate',
  },
  {
    id: 'pass-1029',
    passcode: '1029',
    visitorType: 'service',
    visitorName: 'Ramesh Carpenter',
    visitorPhone: '+91 91234 56789',
    serviceCategory: 'Carpentry',
    flatCode: '1204',
    tower: 'Tower B',
    societyName: 'Lakeview Residency',
    expectedDate: 'Tomorrow (07 Sep 2026)',
    expectedTimeSlot: '11:00 AM – 01:00 PM',
    status: 'active',
    createdAt: 'Yesterday',
    validUntil: '07 Sep, 02:00 PM',
    gateName: 'Service Gate #3',
    notes: 'Kitchen cabinet repair',
  },
];
