import type { VisitLog } from '../../domains/visitors';

export const mockVisitorHistory: VisitLog[] = [
  {
    id: 'log-101',
    visitorPassId: 'pass-8492',
    visitorName: 'Rahul Sharma',
    visitorType: 'guest',
    date: '06 Sep 2026',
    entryTime: '06:34 PM',
    exitTime: '08:12 PM',
    status: 'checked_out',
    flatCode: '1204',
    gateOfficer: 'Officer R. Singh (Main Gate)',
  },
  {
    id: 'log-102',
    visitorPassId: 'pass-3301',
    visitorName: 'Cab Driver (MH 02 EQ 8821)',
    visitorType: 'cab',
    date: '05 Sep 2026',
    entryTime: '09:10 AM',
    exitTime: '09:15 AM',
    status: 'checked_out',
    flatCode: '1204',
    gateOfficer: 'Officer K. Yadav (Main Gate)',
  },
  {
    id: 'log-103',
    visitorPassId: 'pass-1200',
    visitorName: 'E-commerce Courier Agent',
    visitorType: 'delivery',
    date: '04 Sep 2026',
    entryTime: '03:45 PM',
    exitTime: '03:52 PM',
    status: 'checked_out',
    flatCode: '1204',
    gateOfficer: 'Officer R. Singh (Main Gate)',
  },
  {
    id: 'log-104',
    visitorPassId: 'pass-0092',
    visitorName: 'Unverified Walk-in',
    visitorType: 'guest',
    date: '03 Sep 2026',
    entryTime: '05:00 PM',
    status: 'cancelled',
    flatCode: '1204',
    gateOfficer: 'Officer R. Singh (Main Gate)',
  },
];
