import type { PaymentRecord } from '../../domains/payments';

export const mockPaymentHistory: PaymentRecord[] = [
  {
    id: 'PAY-099',
    category: 'maintenance',
    title: 'August 2026 Maintenance Dues',
    amount: 4250,
    dueDate: '2026-08-15',
    status: 'PAID',
    period: 'Aug 2026',
    description:
      'Monthly society maintenance fee covering security, common area maintenance, and lift operations.',
    accountReference: 'LVR-1204-MNT-AUG26',
    paymentDate: '12 Aug 2026, 04:15 PM',
    transactionId: 'TXN-89320149',
    paymentMethod: 'upi',
    receipt: {
      receiptNumber: 'REC-2026-89320',
      transactionId: 'TXN-89320149',
      paidAmount: 4250,
      paymentDate: '12 Aug 2026, 04:15 PM',
      paymentMethod: 'upi',
      payerName: 'Sarvesh Kulkarni',
      flatCode: 'Flat 1204',
      tower: 'Tower B',
      societyName: 'Lakeview Residency',
      category: 'maintenance',
      itemTitle: 'August 2026 Maintenance Dues',
      period: 'Aug 2026',
    },
  },
  {
    id: 'PAY-098',
    category: 'amenity',
    title: 'Clubhouse Tennis Court Slot Booking',
    amount: 350,
    dueDate: '2026-08-04',
    status: 'PAID',
    period: '04 Aug 2026 (06:00 PM - 07:00 PM)',
    description: 'Hourly booking fee for Tennis Court #1 lighting and equipment usage.',
    accountReference: 'LVR-1204-AMN-TC01',
    paymentDate: '04 Aug 2026, 10:30 AM',
    transactionId: 'TXN-78219033',
    paymentMethod: 'card',
    receipt: {
      receiptNumber: 'REC-2026-78219',
      transactionId: 'TXN-78219033',
      paidAmount: 350,
      paymentDate: '04 Aug 2026, 10:30 AM',
      paymentMethod: 'card',
      payerName: 'Sarvesh Kulkarni',
      flatCode: 'Flat 1204',
      tower: 'Tower B',
      societyName: 'Lakeview Residency',
      category: 'amenity',
      itemTitle: 'Clubhouse Tennis Court Slot Booking',
      period: '04 Aug 2026',
    },
  },
  {
    id: 'PAY-097',
    category: 'electricity',
    title: 'Sub-meter Electricity Bill (July 2026)',
    amount: 2840,
    dueDate: '2026-07-25',
    status: 'PAID',
    period: 'Jul 2026',
    description: 'Monthly flat electricity meter consumption bill (355 kWh @ ₹8.00/unit).',
    accountReference: 'LVR-1204-ELE-JUL26',
    paymentDate: '25 Jul 2026, 02:20 PM',
    transactionId: 'TXN-66104822',
    paymentMethod: 'net_banking',
    receipt: {
      receiptNumber: 'REC-2026-66104',
      transactionId: 'TXN-66104822',
      paidAmount: 2840,
      paymentDate: '25 Jul 2026, 02:20 PM',
      paymentMethod: 'net_banking',
      payerName: 'Sarvesh Kulkarni',
      flatCode: 'Flat 1204',
      tower: 'Tower B',
      societyName: 'Lakeview Residency',
      category: 'electricity',
      itemTitle: 'Sub-meter Electricity Bill (July 2026)',
      period: 'Jul 2026',
    },
  },
  {
    id: 'PAY-096',
    category: 'parking',
    title: 'Visitor Parking Overtime Surcharge',
    amount: 150,
    dueDate: '2026-07-18',
    status: 'FAILED',
    period: '18 Jul 2026',
    description: 'Additional visitor parking fee for overnight Guest Parking Slot V-04.',
    accountReference: 'LVR-1204-PRK-OVT',
    paymentDate: '18 Jul 2026, 08:45 PM',
    transactionId: 'TXN-55019388',
    paymentMethod: 'upi',
    failureReason: 'Bank gateway timeout during OTP authorization. Transaction reversed.',
  },
];
