import type {
  SecretaryResidentRecord,
  SecretaryNoticeItem,
  CanonicalBillingRecord,
  CommitteeMemberRecord,
} from './types';

export const INITIAL_SECRETARY_RESIDENTS: SecretaryResidentRecord[] = [
  {
    id: 'res-1',
    name: 'Sarvesh Kulkarni',
    flatNumber: '1204',
    blockWing: 'Block B',
    canonicalDisplay: 'Tower B · Flat 1204',
    type: 'Owner',
    phone: '+91 98765 43210',
    email: 'sarvesh.kulkarni@example.com',
    vehiclesCount: 2,
    familyCount: 4,
    status: 'Active',
    submittedAt: '2026-01-15',
    kycDocType: 'Sale Deed & Aadhaar Verified',
    approvalNote: 'Verified flat ownership document.',
  },
  {
    id: 'res-2',
    name: 'Mayuri Udar',
    flatNumber: '101',
    blockWing: 'Block A',
    canonicalDisplay: 'Block A · Flat 101',
    type: 'Owner',
    phone: '+91 98200 12345',
    email: 'mayuri.udar@greenvalley.org',
    vehiclesCount: 1,
    familyCount: 3,
    status: 'Active',
    submittedAt: '2025-11-10',
    kycDocType: 'Registry Copy Verified',
    approvalNote: 'Secretary & Managing Committee Member.',
  },
  {
    id: 'res-3',
    name: 'Rajesh & Sunita Verma',
    flatNumber: '304',
    blockWing: 'Block A',
    canonicalDisplay: 'Block A · Flat 304',
    type: 'Owner',
    phone: '+91 98111 22334',
    email: 'rajesh.verma@example.com',
    vehiclesCount: 2,
    familyCount: 5,
    status: 'Active',
    submittedAt: '2026-02-01',
    kycDocType: 'Property Deed Verified',
    approvalNote: 'Chairman of Society Committee.',
  },
  {
    id: 'res-4',
    name: 'Ananya Sharma',
    flatNumber: '402',
    blockWing: 'Block B',
    canonicalDisplay: 'Tower B · Flat 402',
    type: 'Tenant',
    phone: '+91 97654 32109',
    email: 'ananya.sharma@example.com',
    vehiclesCount: 1,
    familyCount: 2,
    status: 'Active',
    submittedAt: '2026-04-12',
    kycDocType: 'Registered Rent Agreement',
    approvalNote: 'Owner consent verified.',
  },
  {
    id: 'res-5',
    name: 'Priya & Vikram Nair',
    flatNumber: '701',
    blockWing: 'Block C',
    canonicalDisplay: 'Block C · Flat 701',
    type: 'Owner',
    phone: '+91 99887 76655',
    email: 'vikram.nair@example.com',
    vehiclesCount: 3,
    familyCount: 4,
    status: 'Active',
    submittedAt: '2026-03-20',
    kycDocType: 'Share Certificate Verified',
    approvalNote: 'Treasurer of Society Committee.',
  },
  {
    id: 'res-6',
    name: 'Rohan Mehta',
    flatNumber: '203',
    blockWing: 'Block C',
    canonicalDisplay: 'Block C · Flat 203',
    type: 'Tenant',
    phone: '+91 91234 56780',
    email: 'rohan.mehta@example.com',
    vehiclesCount: 1,
    familyCount: 1,
    status: 'Pending Verification',
    submittedAt: '2026-09-08',
    kycDocType: 'Notarized Rent Agreement & Passport Copy',
    approvalNote: 'Awaiting Secretary KYC document audit.',
  },
];

export const INITIAL_SECRETARY_NOTICES: SecretaryNoticeItem[] = [
  {
    id: 'notif-101',
    title: 'Annual Society General Body Meeting (AGM) Scheduled',
    category: 'General Notice',
    priority: 'Important',
    targetAudience: 'All Blocks',
    content:
      'The Annual General Body Meeting for Green Valley Society will be held on Sunday, September 20th at 10:30 AM in the Main Clubhouse. Agenda items include annual financial audit, security contract renewal, and solar panel installation proposal.',
    status: 'Published',
    createdAt: '2026-09-05',
    publishedAt: '2026-09-05 09:00 AM',
    authorName: 'Mayuri Udar',
    authorRole: 'Society Secretary',
    acknowledgedCount: 42,
  },
  {
    id: 'notif-102',
    title: 'Overhead Tank Cleaning & Water Supply Suspension',
    category: 'Maintenance Alert',
    priority: 'Urgent',
    targetAudience: 'All Blocks',
    content:
      'Quarterly cleaning of main overhead water tanks is scheduled for Tuesday, September 15th between 10:00 AM and 04:00 PM. Water supply will be suspended during this window. Residents are requested to store adequate water.',
    status: 'Published',
    createdAt: '2026-09-08',
    publishedAt: '2026-09-08 08:30 AM',
    authorName: 'Mayuri Udar',
    authorRole: 'Society Secretary',
    acknowledgedCount: 68,
  },
  {
    id: 'notif-103',
    title: 'Ganesh Chaturthi Celebration & Cultural Committee Signup',
    category: 'Event / Celebration',
    priority: 'Normal',
    targetAudience: 'All Blocks',
    content:
      'Cultural committee invites volunteers and donations for the upcoming 5-day Ganesh Utsav in the central courtyard. Registration open at society office.',
    status: 'Published',
    createdAt: '2026-09-01',
    publishedAt: '2026-09-01 11:00 AM',
    authorName: 'Rajesh Verma',
    authorRole: 'Chairman',
    acknowledgedCount: 51,
  },
];

export const INITIAL_CANONICAL_BILLING: CanonicalBillingRecord[] = [
  {
    id: 'PAY-101',
    billNumber: 'BILL-2026-09-1204',
    accountReference: 'GVS-1204-MNT-SEP26',
    billingCycle: 'Sep 2026',
    category: 'maintenance',
    title: 'September 2026 Maintenance Dues',
    residentName: 'Sarvesh Kulkarni',
    flatNumber: '1204',
    blockWing: 'Block B',
    canonicalDisplay: 'Tower B · Flat 1204',
    totalAmount: 4250,
    amountPaid: 0,
    outstandingAmount: 4250,
    dueDate: '2026-09-15',
    status: 'DUE',
    description:
      'Monthly society maintenance fee covering 24/7 gate security, common area housekeeping, lift AMC, water pump operations, and garden landscaping.',
  },
  {
    id: 'PAY-102',
    billNumber: 'BILL-2026-Q3-1204',
    accountReference: 'GVS-1204-PRK-Q3',
    billingCycle: 'Q3 2026 (Jul - Sep)',
    category: 'parking',
    title: 'Q3 Parking & EV Socket Charge',
    residentName: 'Sarvesh Kulkarni',
    flatNumber: '1204',
    blockWing: 'Block B',
    canonicalDisplay: 'Tower B · Flat 1204',
    totalAmount: 1200,
    amountPaid: 0,
    outstandingAmount: 1200,
    dueDate: '2026-09-01',
    status: 'OVERDUE',
    description:
      'Quarterly basement parking slot B-12 maintenance fee and dedicated EV socket access.',
  },
  {
    id: 'PAY-099',
    billNumber: 'BILL-2026-08-1204',
    accountReference: 'GVS-1204-MNT-AUG26',
    billingCycle: 'Aug 2026',
    category: 'maintenance',
    title: 'August 2026 Maintenance Dues',
    residentName: 'Sarvesh Kulkarni',
    flatNumber: '1204',
    blockWing: 'Block B',
    canonicalDisplay: 'Tower B · Flat 1204',
    totalAmount: 4250,
    amountPaid: 4250,
    outstandingAmount: 0,
    dueDate: '2026-08-15',
    status: 'PAID',
    paidAt: '12 Aug 2026, 04:15 PM',
    paymentMethod: 'upi',
    description:
      'Monthly society maintenance fee covering security, common area maintenance, and lift operations.',
  },
  {
    id: 'PAY-103',
    billNumber: 'BILL-2026-09-0101',
    accountReference: 'GVS-0101-MNT-SEP26',
    billingCycle: 'Sep 2026',
    category: 'maintenance',
    title: 'September 2026 Maintenance Dues',
    residentName: 'Mayuri Udar',
    flatNumber: '101',
    blockWing: 'Block A',
    canonicalDisplay: 'Block A · Flat 101',
    totalAmount: 4250,
    amountPaid: 4250,
    outstandingAmount: 0,
    dueDate: '2026-09-15',
    status: 'PAID',
    paidAt: '02 Sep 2026, 11:30 AM',
    paymentMethod: 'net_banking',
    description: 'Monthly maintenance dues paid in advance.',
  },
  {
    id: 'PAY-104',
    billNumber: 'BILL-2026-09-0304',
    accountReference: 'GVS-0304-MNT-SEP26',
    billingCycle: 'Sep 2026',
    category: 'maintenance',
    title: 'September 2026 Maintenance Dues',
    residentName: 'Rajesh & Sunita Verma',
    flatNumber: '304',
    blockWing: 'Block A',
    canonicalDisplay: 'Block A · Flat 304',
    totalAmount: 4250,
    amountPaid: 4250,
    outstandingAmount: 0,
    dueDate: '2026-09-15',
    status: 'PAID',
    paidAt: '05 Sep 2026, 02:15 PM',
    paymentMethod: 'upi',
    description: 'Monthly maintenance fee paid.',
  },
  {
    id: 'PAY-105',
    billNumber: 'BILL-2026-09-0203',
    accountReference: 'GVS-0203-MNT-SEP26',
    billingCycle: 'Sep 2026',
    category: 'maintenance',
    title: 'September 2026 Maintenance Dues',
    residentName: 'Rohan Mehta',
    flatNumber: '203',
    blockWing: 'Block C',
    canonicalDisplay: 'Block C · Flat 203',
    totalAmount: 3100,
    amountPaid: 0,
    outstandingAmount: 3100,
    dueDate: '2026-09-15',
    status: 'DUE',
    description: 'Pro-rated maintenance dues for new tenant registration.',
  },
];

export const INITIAL_COMMITTEE_ROSTER: CommitteeMemberRecord[] = [
  {
    id: 'cm-1',
    name: 'Mayuri Udar',
    designation: 'Secretary',
    flatNumber: '101',
    blockWing: 'Block A',
    canonicalDisplay: 'Block A · Flat 101',
    phone: '+91 98200 12345',
    email: 'secretary@greenvalleysociety.org',
    avatarUrl:
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80',
    termDuration: '2025 - 2027 (Term 2)',
  },
  {
    id: 'cm-2',
    name: 'Rajesh Verma',
    designation: 'Chairman',
    flatNumber: '304',
    blockWing: 'Block A',
    canonicalDisplay: 'Block A · Flat 304',
    phone: '+91 98111 22334',
    email: 'chairman@greenvalleysociety.org',
    avatarUrl:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    termDuration: '2025 - 2027',
  },
  {
    id: 'cm-3',
    name: 'Vikram Nair',
    designation: 'Treasurer',
    flatNumber: '701',
    blockWing: 'Block C',
    canonicalDisplay: 'Block C · Flat 701',
    phone: '+91 99887 76655',
    email: 'treasurer@greenvalleysociety.org',
    avatarUrl:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=250&q=80',
    termDuration: '2025 - 2027',
  },
  {
    id: 'cm-4',
    name: 'Ananya Sharma',
    designation: 'Joint Secretary',
    flatNumber: '402',
    blockWing: 'Block B',
    canonicalDisplay: 'Tower B · Flat 402',
    phone: '+91 97654 32109',
    email: 'jointsec@greenvalleysociety.org',
    avatarUrl:
      'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=250&q=80',
    termDuration: '2025 - 2027',
  },
];
