import type { GateHistoryRecord } from '../../domains/guard/types';

export const INITIAL_GATE_HISTORY: GateHistoryRecord[] = [
  {
    id: 'hist-01',
    visitorId: 'pass-7782',
    visitorName: 'Swiggy Delivery (Karan)',
    visitorType: 'delivery',
    residentName: 'Ananya Sharma',
    flatCode: 'Block B · Flat 402',
    action: 'checked_out',
    actionLabel: 'Checked Out',
    timestamp: '10 Sep 2026, 02:22 PM',
    gateName: 'Gate #1 Main Entrance',
    gateOfficer: 'Officer R. Singh',
    notes: 'Completed parcel dropoff',
  },
  {
    id: 'hist-02',
    visitorId: 'pass-3341',
    visitorName: 'Ankit Verma',
    visitorType: 'guest',
    residentName: 'Mayuri Udar',
    flatCode: 'Block A · Flat 101',
    action: 'checked_in',
    actionLabel: 'Checked In',
    timestamp: '10 Sep 2026, 11:20 AM',
    gateName: 'Gate #1 Main Entrance',
    gateOfficer: 'Officer R. Singh',
  },
  {
    id: 'hist-03',
    visitorId: 'pass-expired-99',
    visitorName: 'Urban Company Cleaner',
    visitorType: 'service',
    residentName: 'Rohan Mehta',
    flatCode: 'Block C · Flat 203',
    action: 'entry_rejected',
    actionLabel: 'Entry Rejected',
    timestamp: '10 Sep 2026, 09:45 AM',
    gateName: 'Gate #1 Main Entrance',
    gateOfficer: 'Officer R. Singh',
    rejectionReason: 'Pass Expired / Invalid Identification',
  },
];
