import type { GuardVisitor } from '../../domains/guard/types';

export const INITIAL_GUARD_VISITORS: GuardVisitor[] = [
  {
    id: 'pass-8492',
    passcode: '8492',
    name: 'Rahul Sharma',
    phone: '+91 98765 00112',
    visitorType: 'guest',
    visitorTypeLabel: 'Personal Guest',
    residentName: 'Sarvesh Kulkarni',
    flatCode: 'Flat 1204',
    tower: 'Tower B',
    societyName: 'Lakeview Residency',
    vehicleNumber: 'MH 12 AB 1234',
    expectedDate: 'Today',
    expectedTimeSlot: '06:00 PM – 09:00 PM',
    status: 'expected',
    verificationStatus: 'valid',
    createdAt: '10 Sep 2026, 04:30 PM',
    gateName: 'Gate #1 Main Entrance',
    gateOfficer: 'Officer R. Singh',
    notes: 'Dinner guest for flat 1204',
  },
  {
    id: 'pass-9102',
    passcode: '9102',
    name: 'Food Delivery Agent (Zomato)',
    phone: '+91 91122 33445',
    visitorType: 'delivery',
    visitorTypeLabel: 'Food Delivery',
    companyName: 'Zomato',
    residentName: 'Sarvesh Kulkarni',
    flatCode: 'Flat 1204',
    tower: 'Tower B',
    societyName: 'Lakeview Residency',
    vehicleNumber: 'MH 14 CD 5678',
    expectedDate: 'Today',
    expectedTimeSlot: 'Immediate (15 mins)',
    status: 'approval_required',
    verificationStatus: 'approval_required',
    createdAt: '10 Sep 2026, 05:45 PM',
    arrivedAt: '10 Sep 2026, 05:58 PM',
    gateName: 'Gate #1 Main Entrance',
    gateOfficer: 'Officer R. Singh',
    notes: 'Order #ZOM-99201',
  },
  {
    id: 'pass-5012',
    passcode: '5012',
    name: 'Ramesh Carpenter',
    phone: '+91 98333 44556',
    visitorType: 'service',
    visitorTypeLabel: 'Home Service',
    serviceCategory: 'Carpentry Maintenance',
    residentName: 'Sarvesh Kulkarni',
    flatCode: 'Flat 1204',
    tower: 'Tower B',
    societyName: 'Lakeview Residency',
    expectedDate: 'Today',
    expectedTimeSlot: '10:00 AM – 02:00 PM',
    status: 'expected',
    verificationStatus: 'valid',
    createdAt: '10 Sep 2026, 08:00 AM',
    gateName: 'Gate #1 Main Entrance',
    gateOfficer: 'Officer R. Singh',
  },
  {
    id: 'pass-3341',
    passcode: '3341',
    name: 'Ankit Verma',
    phone: '+91 98222 11009',
    visitorType: 'guest',
    visitorTypeLabel: 'Family Guest',
    residentName: 'Mayuri Udar',
    flatCode: 'Flat 101',
    tower: 'Block A',
    societyName: 'Green Valley Society',
    vehicleNumber: 'MH 02 EF 9081',
    expectedDate: 'Today',
    expectedTimeSlot: '11:00 AM – 05:00 PM',
    status: 'checked_in',
    verificationStatus: 'valid',
    createdAt: '10 Sep 2026, 10:15 AM',
    checkedInAt: '10 Sep 2026, 11:20 AM',
    gateName: 'Gate #1 Main Entrance',
    gateOfficer: 'Officer R. Singh',
  },
  {
    id: 'pass-1089',
    passcode: '1089',
    name: 'Priya Saxena',
    phone: '+91 97111 55443',
    visitorType: 'guest',
    visitorTypeLabel: 'Friend',
    residentName: 'Rajesh Verma',
    flatCode: 'Flat 304',
    tower: 'Block A',
    societyName: 'Green Valley Society',
    expectedDate: 'Today',
    expectedTimeSlot: '01:00 PM – 08:00 PM',
    status: 'checked_in',
    verificationStatus: 'valid',
    createdAt: '10 Sep 2026, 12:00 PM',
    checkedInAt: '10 Sep 2026, 01:15 PM',
    gateName: 'Gate #1 Main Entrance',
    gateOfficer: 'Officer R. Singh',
  },
  {
    id: 'pass-7782',
    passcode: '7782',
    name: 'Swiggy Delivery (Karan)',
    visitorType: 'delivery',
    visitorTypeLabel: 'Food Delivery',
    companyName: 'Swiggy',
    residentName: 'Ananya Sharma',
    flatCode: 'Flat 402',
    tower: 'Block B',
    societyName: 'Green Valley Society',
    expectedDate: 'Today',
    expectedTimeSlot: '02:00 PM',
    status: 'checked_out',
    verificationStatus: 'valid',
    createdAt: '10 Sep 2026, 01:50 PM',
    checkedInAt: '10 Sep 2026, 02:05 PM',
    checkedOutAt: '10 Sep 2026, 02:22 PM',
    gateName: 'Gate #1 Main Entrance',
    gateOfficer: 'Officer R. Singh',
  },
];
